name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Hello Action!
    - name: git status
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        git config --global credential.helper 'cache --timeout=3600'
        echo "===========   ENV ============"
        env
        echo "===========   LS ============"
        ls -lth
        echo "$(date): $(whoami)Test: ${GITHUB_REPOSITORY}" >> .github/test.log
        echo "===========   git config ============"

        git config -l
        echo "===========   git status ============"
        git checkout -b test
        git status
        echo "===========   git config email ============"
        git config --global user.email "wxdlong@qq.com"
        echo "===========   git config name ============"
        git config --global user.name "wxdlong"
        echo "===========   git add  ============"
        git add .github/test.log
        echo -e " git remote :\n $(git remote -v)"
         echo -e " git branch :\n $(git branch -v)"
        echo "===========   git commit ============"
        git commit -m "just test"
        echo "===========   git push ============"
        
        git subtree push --prefix=.github https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git abc
