name: Deploy to github page on push blog
on:
  push:
    branches:
      - blog

jobs:
  hugo-action:
    runs-on: ubuntu-latest
    name: Build Hugo Pages
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Login to the Github docker
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        docker login docker.pkg.github.com -u wxdlong -p ${ACCESS_TOKEN}

    - name: Hugo site and deploy 2 github page
      uses: wxdlong/hugo-action@master
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        cname: 'https://ycat.top'
        branch: 'master'