name: Deploy to github page
on:
  push:
    branches:
      - blog

jobs:
  hugo-action:
    runs-on: ubuntu-latest
    name: Build Hugo Pages
    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: Hugo Site and Deploy 2 Github Page
      uses: wxdlong/hugo-action@master
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        cname: 'https://ycat.top'
        branch: 'master'