name: Deploy to github page
on:
  push:
    branches:
      - blog

jobs:
  hugo-action:
    runs-on: ubuntu-latest
    name: build hugo pages
    steps:
    - uses: actions/checkout@v1
    - name: Hello hugo
      id: hugo
      uses: wxdlong/hugo-action@master
    - name: Push to page branch
      uses: wxdlong/push-action@master
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        cname: 'https://ycat.top'
        branch: 'master'