name: Deploy to github page
on: [push]

jobs:
  hugo-action:
    runs-on: ubuntu-latest
    name: build hugo pages
    steps:
    - uses: actions/checkout@v1
    - name: Hello hugo
      id: hugo
      uses: wxdlong/hugo-action@master
    # Use the output from the `hello` step
    - name: Get the output time
      run: |
        ls -lth